### PR TITLE
New feature: Screenshot for a download

### PR DESCRIPTION
**Pull request by KratorD**
Add the possibility of associate a screenshot image to a download (entity)

### CODE REVIEW

**Comment by craigh** [comment]
it doesn't appear you've added any upgrade path for this. will you please do so and open another PR.

**Comment by KratorD** [comment]
What do you mean with "upgrade path"? I don't understand.

**Comment by craigh** [comment]
I mean there is no upgrade routine for the module. This has nothing to do with Git (or github). Since the entity has changed (among other reasons) the module needs an upgrade routine in the Install file and also the version needs to get bumped.

**Comment by KratorD** [comment]
Oh, sorry! Perfect, I will see this

**Comment by KratorD** [comment]
I have a question about this.
I have tried with this line
`DoctrineHelper::updateSchema($this->entityManager, 'Downloads_Entity_Download');`
But this dont add the field to the DB, is it correct?
I need insert the field in the DB with a sql sentence, is true?

Thanks

**Comment by craigh** [comment]
the updateSchema _should_ work. have you tried it?

**Comment by KratorD** [comment]
OOOOOk, the second parameter is an array, so the correct line is
`DoctrineHelper::updateSchema($this->entityManager, array('Downloads_Entity_Download'));`

Thanks!

**Pull request merged**
